services:
    runner:
        build: .
        container_name: github-actions-runner
        restart: unless-stopped
        platform: linux/arm64
        environment:
            - REPO_URL
            - ACCESS_TOKEN
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - runner_data:/actions-runner
        networks:
            - runner_network

volumes:
    runner_data:

networks:
    runner_network:
        name: runner_network
        driver: bridge
