# =========================================================================
#  共通 ＆ ローカル環境（デフォルト）の設定
# =========================================================================
spring:
    application:
        name: verify
    messages:
        basename: messages
        encoding: UTF-8
    web:
        locale: ja # デフォルトのロケールを日本語に固定

logging:
    level:
        root: INFO
        '[com.github.k.genki0913.verify]': DEBUG
    pattern:
        # どのログレベルが表示されても縦のラインが揃うように5桁分確保する
        # ローカル用：クラス名のみ(0) ＆ 5桁揃えカラフル仕様
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%highlight(%-5level)] %clr(%logger{0}){magenta} - %msg%n'

---
# ↑この「---」が、1つのファイル内で環境を隔てる境界線

# =========================================================================
# AWS（dev）環境専用の上書き設定
#
# 【設計理由（マルチドキュメント構成を採用）】
# 1. 1ファイルに集約することで、環境間の設定漏れや迷子を100%防止するため。
# 2. クラウド環境では機密情報を「環境変数」で扱うため、yaml自体は肥大化しないため。
# =========================================================================
spring:
    config:
        activate:
            on-profile: dev # プロファイル「dev」が指定された時だけ、ここから下で上書き

logging:
    pattern:
        # AWS用：CloudWatchで見やすいようにフルパッケージ名(100) ＆ 色なし(5桁揃え)
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %logger{100} - %msg%n'
