services:
    ci-spring-db-test:
        image: postgres:18
        container_name: ${DB_CONTAINER_NAME:-ci-spring-db-test}
        environment:
            POSTGRES_DB: ${POSTGRES_TEST_DATABASE_NAME}
            POSTGRES_USER: ${POSTGRES_TEST_USER}
            POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
        volumes:
            - db-test-store:/var/lib/postgresql
            - ./postgres_logs:/var/log/postgresql
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_TEST_USER} -d ${POSTGRES_TEST_DATABASE_NAME}']
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - runner_network

volumes:
    db-test-store:

networks:
    runner_network:
        external: true
