name: CI for Local Runner

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Show me the environment
              run: |
                  echo "ランナーが動いている場所: $(hostname)"
                  echo "Javaのバージョン:"
                  java -version
                  echo "Dockerのバージョン:"
                  docker --version

            - name: Start Test Database
              run: docker compose -f .devcontainer/compose.yaml up -d spring-db-test

            #- name: Run Unit and Integration Tests
            #  env:
            #      DB_TEST_HOST: localhost
            #      DB_TEST_PORT: 25432
            #      POSTGRES_TEST_DATABASE_NAME: spring-app_test
            #      POSTGRES_TEST_USER: test_user
            #      POSTGRES_TEST_PASSWORD: rootroot
            #  run: |
            #      ./mvnw test

            - name: Remove Test Database
              if: always()
              run: docker compose -f .devcontainer/compose.yaml down -v
