name: CI for Local Runner

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Show me the environment
              run: |
                  echo "ランナーが動いている場所: $(hostname)"
                  echo "Javaのバージョン:"
                  java -version
                  echo "Dockerのバージョン:"
                  docker --version

            - name: Hello World
              run: echo "Hello! 自分のPCのランナーで起動"